org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -Djava.io.tmpdir=/home/ben-10/.gradle/tmp -Djdk.tls.client.protocols=TLSv1.2 -Dhttps.protocols=TLSv1.2 -Dorg.gradle.internal.http.socketTimeout=120000 -Dorg.gradle.internal.http.connectionTimeout=120000
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
android.suppressUnsupportedCompileSdk=35
android.sdk.path=/home/ben-10/Android/Sdk
android.sdk.home=/home/ben-10/.android
